pub mod account;
pub mod admin;
pub mod contact;
pub mod home;
pub mod imprint;
pub mod login;
pub mod logout;
pub mod not_found;
pub mod privacy;
pub mod protected;

pub use account::{AccountPage, AccountPasswordPage, AccountProfilePage, AccountWebauthnPage};
pub use admin::AdminPage;
pub use contact::Contact;
pub use home::Home;
pub use imprint::Imprint;
pub use login::LoginPage;
pub use logout::LogoutPage;
pub use not_found::NotFound;
pub use privacy::Privacy;
pub use protected::Protected;
