use crate::i18n::*;
use leptos::prelude::*;
use leptos_i18n::Locale as LocaleTrait;
use leptos_meta::Link as MetaLink;

/// Central list of supported locales generated by `leptos_i18n`.
#[inline]
pub fn supported_locales() -> &'static [Locale] {
    Locale::get_all()
}

/// Parse a locale code (e.g. `"de"`, `"en"`) into a `Locale`.
#[inline]
pub fn locale_from_code(code: &str) -> Option<Locale> {
    code.parse().ok()
}

/// Get locale code (e.g. `"de"`, `"en"`).
#[inline]
pub fn locale_code(locale: Locale) -> &'static str {
    locale.as_str()
}

/// Optional display label helper for locale selectors.
#[inline]
pub fn locale_label(locale: Locale) -> &'static str {
    match locale {
        Locale::de => "DE",
        Locale::en => "EN",
    }
}

/// Normalize an href to an absolute in-app path while preserving external/special links.
///
/// - `""` -> `"/"`
/// - `"contact"` -> `"/contact"`
/// - `"/contact"` -> `"/contact"`
/// - `http://...`, `https://...`, `mailto:...`, `tel:...`, `#...` are returned unchanged.
#[inline]
pub fn lp(_locale: Locale, href: &str) -> String {
    let h = href.trim();

    if h.is_empty() {
        return "/".to_string();
    }

    if h.starts_with("http://")
        || h.starts_with("https://")
        || h.starts_with("mailto:")
        || h.starts_with("tel:")
        || h.starts_with('#')
    {
        return h.to_string();
    }

    let p = h.trim_start_matches('/');
    if p.is_empty() {
        "/".to_string()
    } else {
        format!("/{}", p)
    }
}

/// Build an absolute URL from base URL + localized path.
///
/// If `href` is already external (`http`, `https`, `mailto`, `tel`, `#`), it is returned unchanged.
#[inline]
pub fn absolute_url(base_url: &str, locale: Locale, href: &str) -> String {
    let normalized = lp(locale, href);

    if normalized.starts_with("http://")
        || normalized.starts_with("https://")
        || normalized.starts_with("mailto:")
        || normalized.starts_with("tel:")
        || normalized.starts_with('#')
    {
        return normalized;
    }

    let base = base_url.trim().trim_end_matches('/');
    if base.is_empty() {
        normalized
    } else {
        format!("{base}{normalized}")
    }
}

/// Resolve application base URL for SEO absolute links.
///
/// Uses `APP_BASE_URL` when present.
#[inline]
pub fn app_base_url() -> Option<String> {
    std::env::var("APP_BASE_URL")
        .ok()
        .map(|v| v.trim().to_string())
        .filter(|v| !v.is_empty())
}

/// Route identity for alternate link generation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AlternateRoute {
    Contact,
    Imprint,
    Privacy,
    Home,
    Login,
    Logout,
}

impl AlternateRoute {
    #[inline]
    pub fn localized_path(self, locale: Locale) -> &'static str {
        match self {
            AlternateRoute::Contact => td_string!(locale, routes.contact_path),
            AlternateRoute::Imprint => td_string!(locale, routes.imprint_path),
            AlternateRoute::Privacy => td_string!(locale, routes.privacy_path),
            AlternateRoute::Home => td_string!(locale, routes.home_path),
            AlternateRoute::Login => td_string!(locale, routes.login_path),
            AlternateRoute::Logout => td_string!(locale, routes.logout_path),
        }
    }
}

/// Render `<link rel="alternate" hreflang="...">` tags for all locales.
///
/// - If `base_url` is provided (or `APP_BASE_URL` exists), links are absolute.
/// - Otherwise links are rendered as normalized app-relative paths.
#[component]
pub fn AlternateLinks(
    route: AlternateRoute,
    #[prop(optional, into)] base_url: Option<String>,
) -> impl IntoView {
    let resolved_base = base_url.or_else(app_base_url);

    let links = supported_locales()
        .iter()
        .copied()
        .map(|locale| {
            let href = match &resolved_base {
                Some(base) => absolute_url(base, locale, route.localized_path(locale)),
                None => lp(locale, route.localized_path(locale)),
            };

            view! {
                <MetaLink
                    rel="alternate"
                    hreflang=locale.as_str()
                    href=href
                />
            }
        })
        .collect_view();

    view! { <>{links}</> }
}
