//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::user_roles::Entity as UserRoles;
pub use super::users::Entity as Users;
pub use super::webauthn_credentials::Entity as WebauthnCredentials;
