//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "role_permissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub permission_id: i64,
    #[sea_orm(
        belongs_to,
        from = "permission_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub permissions: HasOne<super::permissions::Entity>,
    #[sea_orm(
        belongs_to,
        from = "role_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub roles: HasOne<super::roles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
