//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub username: String,
    pub first_name: String,
    pub last_name: String,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    pub status: String,
    pub password_reset_required: bool,
    #[sea_orm(unique)]
    pub webauthn_user_handle: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(has_many)]
    pub webauthn_credentials: HasMany<super::webauthn_credentials::Entity>,
    #[sea_orm(has_many, via = "user_roles")]
    pub roles: HasMany<super::roles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
